#!/bin/bash
# Compatibility wrapper: the index (INDEX.md, index/graph.json, skills/MASTER_INDEX.md,
# skillOverrides) is generated by scripts/generate-index.mjs.
MODE=--write
for arg in "$@"; do
    case "$arg" in --write|--check) MODE="" ;; esac
done
SCRIPT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/generate-index.mjs"
if [ -n "$MODE" ]; then
    exec node "$SCRIPT" "$MODE" "$@"
else
    exec node "$SCRIPT" "$@"
fi
