#!/bin/bash
# Compatibility wrapper: the index (INDEX.md, index/graph.json, skills/MASTER_INDEX.md,
# skillOverrides) is generated by scripts/generate-index.mjs.
exec node "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/generate-index.mjs" --write "$@"
